### ISSUE TITLE
Make supertest-postman npm link-able or installable

### ISSUE THREAD

**Issue by 27escape** [AndrewKeig/supertest-postman#1]
I would like to be able to run supertest-postman in a directory other than the github repo. I have updated package.json to do that and also to add your git repo. index.js also needs a hash-bang line so that it can be executed on unix-like systems
[index.js.txt](https://github.com/AndrewKeig/supertest-postman/files/3750573/index.js.txt)

[package.json.txt](https://github.com/AndrewKeig/supertest-postman/files/3750574/package.json.txt)

I would have submitted a PR but your repo is not open to this

cheers
Kevin

**Comment by AndrewKeig** [comment]
@27escape , fixed this issue. Thanks
